# Generated by Django 5.2.12 on 2026-04-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
