# Generated by Django 5.2.12 on 2026-04-22 11:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_doctor_gender_alter_patient_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
