# Generated by Django 5.2.12 on 2026-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_doctor_phonenumber_alter_patient_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')]),
        ),
    ]
