# Generated by Django 5.2.12 on 2026-04-23 10:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='slot_avaibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(verbose_name='starttime')),
                ('end_time', models.TimeField(verbose_name='endtime')),
                ('is_booked', models.BooleanField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(default=datetime.time(10, 0), verbose_name='starttime')),
                ('end_time', models.TimeField(default=datetime.time(6, 0), verbose_name='endtime')),
                ('slot_duration', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'start_date', 'end_date')},
            },
        ),
    ]
