# Generated by Django 6.0.4 on 2026-04-27 01:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(default=datetime.time(10, 0), verbose_name='starttime')),
                ('end_time', models.TimeField(verbose_name='endtime')),
                ('slot_duration', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='slot_availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(verbose_name='starttime')),
                ('end_time', models.TimeField(verbose_name='endtime')),
                ('is_booked', models.BooleanField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='Doctor.doctorschedule')),
            ],
            options={
                'unique_together': {('schedule', 'date', 'start_time')},
            },
        ),
    ]
