# Generated by Django 5.2.12 on 2026-04-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
        ('Users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklySchedule',
            new_name='DoctorSchedule',
        ),
    ]
