# Generated by Django 5.2.12 on 2026-04-27 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.doctor'),
        ),
        migrations.AddField(
            model_name='slot_availability',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='Doctor.doctorschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='slot_availability',
            unique_together={('schedule', 'date', 'start_time')},
        ),
    ]
