# Generated by Django 5.2.12 on 2026-04-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_rename_weeklyschedule_doctorschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='end_time',
            field=models.TimeField(verbose_name='endtime'),
        ),
    ]
