# Generated by Django 5.2.12 on 2026-04-24 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_alter_doctorschedule_doctor_and_more'),
        ('Users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.doctor'),
        ),
        migrations.AlterField(
            model_name='slot_avaibility',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.doctor'),
        ),
    ]
